apiVersion: apps/v1
kind: Deployment
metadata:
  name: eli456
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eli456
  template:
    metadata:
      labels:
        app: eli456
    spec:
      containers:
      - image: okteto.dev/eli456:latest
        name: eli456
        envFrom:
        - configMapRef:
            name: eli456-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: eli456
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "eli456"
    port: 8080
  selector:
    app: eli456