apiVersion: v1
kind: ConfigMap
metadata:
  name: eli456-config
  labels:
    app: postgres
data:
  PROD_SECRET_KEY : ElizabethCochinota 
  PROD_DATABASE : qqvndewn 
  PROD_USER : qqvndewn 
  PROD_PASSWORD : OUBqModPqnqnR1cHz_bQkVHXsMryS4sB 
  PROD_HOST : rosie.db.elephantsql.com 
  PROD_PORT : "5432"