# Generated by Django 3.1.3 on 2023-02-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreflor', models.TextField(default='')),
                ('tipo', models.TextField(blank=True, default='')),
                ('color', models.TextField(default='')),
                ('cantidad', models.FloatField(default=1.0)),
                ('fecha', models.DateTimeField(blank=True, default=0)),
                ('ocasion', models.TextField(default='')),
                ('precio', models.FloatField(default=0.0)),
                ('formadepago', models.TextField(default='')),
                ('existencias', models.FloatField(default=0.0)),
                ('direccion', models.TextField(blank=True)),
            ],
        ),
    ]
